sudo: false
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run coverage
after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
